### ISSUE TITLE
Move body tag outside block body_base

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/dc_django_utils#34]
At the moment, we define `{% block body_base %}` as an empty block in `dc_base_naked.html`.

This is good because it allows for maximum flexibility, however it also makes some things a little harder.

For example, we currently have three blocks, `extra_site_js`, `in_page_javascript`, `ga_tracking_code` that are only defined in `dc_base.html`, but are defined outside of any block in `dc_base_naked.html`. This means they'll never get rendered on any sites, even if the project template implements them.

The quick win would be to add them to `dc_base_naked.html`, however it's not possible to do this in a way that places the HTML inside the closing of the HTML `body` tag.

A better solution would be something like this:

```jinja
<body {% block body_attrs %}class="ds-width-full"{% endblock block body_attrs %}>
{% block body_base %}
{% endblock body_base %}

{% block extra_site_js %}
{% endblock extra_site_js %}

{% block in_page_javascript %}
{% endblock in_page_javascript %}

{% block ga_tracking_code %}
{% endblock ga_tracking_code %}
</body>
```

This would be a breaking change for apps that use the existing system, as they'd need to remove the `body` tag from their `base.html`, but it would allow for extending the body tag with other blocks.

**Comment by VirginiaDooley** [comment]
In this case, should `dc_base_naked.html` be added as an `includes` template after `</head>` or in another `block` tag?
